{{- if and .Values.loadDefinition.enabled (not .Values.loadDefinition.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-definitions" (include "rabbitmq.fullname" .) }}
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  definitions.json: {{ .Values.loadDefinition.content | toJson | b64enc | quote }}
{{- end }}
