apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}-headless
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
    - name: dist
      port: {{ .Values.service.distPort }}
      targetPort: dist
      protocol: TCP
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
    - name: epmd
      port: 4369
      targetPort: epmd
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - name: prometheus
      port: {{ .Values.service.prometheusPort }}
      targetPort: prometheus
      protocol: TCP
    {{- end }}
  selector:
    {{- include "rabbitmq.labels.matchLabels" (dict "customLabels" .Values.podLabels "context" $) | nindent 4 }}
