{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $password := include "common.secrets.manage" (dict "secret" (include "rabbitmq.fullname" .) "key" "rabbitmq-password" "providedValues" (list "auth.password") "length" 16 "strong" true "context" $) }}
  rabbitmq-password: {{ $password }}
  {{- $erlangCookie := include "common.secrets.manage" (dict "secret" (include "rabbitmq.fullname" .) "key" "rabbitmq-erlang-cookie" "providedValues" (list "auth.erlangCookie") "length" 32 "strong" true "context" $) }}
  rabbitmq-erlang-cookie: {{ $erlangCookie }}
  rabbitmq-host: {{ printf "%s.%s.svc.%s" (include "rabbitmq.fullname" .) (include "rabbitmq.namespace" .) .Values.clusterDomain | b64enc | quote }}
  rabbitmq-amqp-port: {{ (include "rabbitmq.amqpPort" .) | b64enc | quote }}
  rabbitmq-uri: {{ printf "%s://%s:%s@%s.%s.svc.%s:%s" (ternary "amqps" "amqp" .Values.tls.enabled) (urlquery .Values.auth.username) (urlquery ($password | b64dec)) (include "rabbitmq.fullname" .) (include "rabbitmq.namespace" .) .Values.clusterDomain (include "rabbitmq.amqpPort" .) | b64enc | quote }}
{{- end }}
