{{- if eq (include "rabbitmq.serviceAccount.create" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq.serviceAccountName" . }}
  namespace: {{ include "rabbitmq.namespace" . }}
  labels:
    {{- include "rabbitmq.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.serviceAccount.annotations .Values.commonAnnotations) "context" $) | fromYaml }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
