apiVersion: v2
name: generic
description: A generic application Helm chart for deploying any containerized workload
type: application
kubeVersion: ">= 1.24.0-0"
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/emberstack/helm-charts
sources:
  - https://github.com/emberstack/helm-charts
maintainers:
  - name: emberstack
    email: helm-charts@emberstack.com
keywords:
  - generic
  - application
  - deployment
  - cronjob
dependencies:
  - name: common
    version: "1.x.x"
    repository: "file://../common"
