{{- $sa := default dict .Values.serviceAccount -}}
{{- if (include "mssql.serviceAccount.create" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mssql.serviceAccountName" . }}
  namespace: {{ include "mssql.namespace" . }}
  labels:
    {{- include "mssql.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list (default dict $sa.annotations) .Values.commonAnnotations) "context" $) | fromYaml }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ default false $sa.automountServiceAccountToken }}
{{- end }}
