{{- range .Values.httpRoutes }}
{{- $item := . -}}
{{- if eq (include "common.item.enabled" (dict "item" $item)) "true" }}
{{- $fullName := include "common.names.item.fullname" (dict "item" $item "context" $) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.item" (dict "item" $item "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
  {{- include "common.annotations.render" (dict "annotations" (merge (default dict $item.annotations) (default dict $.Values.commonAnnotations)) "context" $) | nindent 2 }}
spec:
  {{- if $item.parentRefs }}
  parentRefs:
    {{- range $item.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .group }}
      group: {{ .group }}
      {{- end }}
      {{- if .kind }}
      kind: {{ .kind }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
      {{- if .port }}
      port: {{ .port }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if $item.hostnames }}
  hostnames:
    {{- range $item.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  {{- if $item.rules }}
  rules:
    {{- toYaml $item.rules | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
