apiVersion: v2
name: nginx-gateway-fabric-extensions
description: A Helm chart for NGINX Gateway Fabric extensions
type: application
version: 1.0.0
appVersion: 1.0.0

icon: https://raw.githubusercontent.com/emberstack/helm-charts/main/src/charts/nginx-gateway-fabric-extensions/icon.png
keywords:
- nginx
- nginx-gateway-fabric
- clientsettingspolicy
- observabilitypolicy
- ratelimitpolicy
home: https://github.com/emberstack/helm-charts
sources:
- https://github.com/emberstack/helm-charts
maintainers:
- name: emberstack
  email: helm-charts@emberstack.com
dependencies:
  - name: common
    version: "1.x.x"
    repository: "file://../common"
