{{- range .Values.appProjects }}
{{- $item := . -}}
{{- if eq (include "common.item.enabled" (dict "item" $item)) "true" }}
{{- $fullName := include "common.names.item.fullname" (dict "item" $item "context" $) }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $fullName }}
  namespace: {{ include "common.names.item.namespace" (dict "item" $item "context" $) }}
  labels:
    {{- include "common.labels.item" (dict "item" $item "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
  {{- include "common.annotations.render" (dict "annotations" (merge (default dict $item.annotations) (default dict $.Values.commonAnnotations)) "context" $) | nindent 2 }}
spec:
  {{- if $item.description }}
  description: {{ $item.description }}
  {{- end }}
  {{- if $item.clusterResourceWhitelist }}
  clusterResourceWhitelist:
    {{- toYaml $item.clusterResourceWhitelist | nindent 4 }}
  {{- end }}
  {{- if $item.clusterResourceBlacklist }}
  clusterResourceBlacklist:
    {{- toYaml $item.clusterResourceBlacklist | nindent 4 }}
  {{- end }}
  {{- if $item.namespaceResourceWhitelist }}
  namespaceResourceWhitelist:
    {{- toYaml $item.namespaceResourceWhitelist | nindent 4 }}
  {{- end }}
  {{- if $item.namespaceResourceBlacklist }}
  namespaceResourceBlacklist:
    {{- toYaml $item.namespaceResourceBlacklist | nindent 4 }}
  {{- end }}
  {{- if $item.destinations }}
  destinations:
    {{- toYaml $item.destinations | nindent 4 }}
  {{- end }}
  {{- if $item.sourceRepos }}
  sourceRepos:
    {{- toYaml $item.sourceRepos | nindent 4 }}
  {{- end }}
  {{- if $item.sourceNamespaces }}
  sourceNamespaces:
    {{- toYaml $item.sourceNamespaces | nindent 4 }}
  {{- end }}
  {{- if $item.orphanedResources }}
  orphanedResources:
    {{- toYaml $item.orphanedResources | nindent 4 }}
  {{- end }}
  {{- if $item.syncWindows }}
  syncWindows:
    {{- toYaml $item.syncWindows | nindent 4 }}
  {{- end }}
  {{- if $item.roles }}
  roles:
    {{- toYaml $item.roles | nindent 4 }}
  {{- end }}
  {{- if $item.signatureKeys }}
  signatureKeys:
    {{- toYaml $item.signatureKeys | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
