{{- range .Values.configMaps }}
{{- $item := . -}}
{{- if eq (include "common.item.enabled" (dict "item" $item)) "true" }}
{{- $fullName := include "common.names.item.fullname" (dict "item" $item "context" $) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  namespace: {{ include "common.names.item.namespace" (dict "item" $item "context" $) }}
  labels:
    {{- include "common.labels.item" (dict "item" $item "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
  {{- include "common.annotations.render" (dict "annotations" (merge (default dict $item.annotations) (default dict $.Values.commonAnnotations)) "context" $) | nindent 2 }}
{{- if or $item.data $item.binaryData }}
{{- if $item.data }}
data:
  {{- toYaml $item.data | nindent 2 }}
{{- end }}
{{- if $item.binaryData }}
binaryData:
  {{- toYaml $item.binaryData | nindent 2 }}
{{- end }}
{{- else }}
data: {}
{{- end }}
{{- if hasKey $item "immutable" }}
immutable: {{ $item.immutable }}
{{- end }}
{{- end }}
{{- end }}
