apiVersion: v2
name: azurite
description: A Helm chart for deploying Azurite (Azure Storage Emulator) on Kubernetes
type: application
kubeVersion: ">= 1.24.0-0"
version: 1.0.0
appVersion: "3.35.0"
home: https://github.com/emberstack/helm-charts
sources:
  - https://github.com/emberstack/helm-charts
maintainers:
  - name: emberstack
    email: helm-charts@emberstack.com
keywords:
  - azurite
  - azure-storage
  - blob
  - queue
  - table
  - emulator
dependencies:
  - name: common
    version: "1.x.x"
    repository: "file://../common"
