{{- range $key, $item := .Values.webApplicationFirewallPolicies }}
{{- $item := merge (dict "name" $key) $item -}}
{{- if eq (include "common.item.enabled" (dict "item" $item)) "true" }}
{{- $fullName := include "common.names.item.fullname" (dict "item" $item "context" $) }}
---
apiVersion: alb.networking.azure.io/v1
kind: WebApplicationFirewallPolicy
metadata:
  name: {{ $fullName }}
  namespace: {{ include "common.names.namespace" $ }}
  labels:
    {{- include "common.labels.item" (dict "item" $item "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
  {{- include "common.annotations.render" (dict "annotations" (merge (default dict $item.annotations) (default dict $.Values.commonAnnotations)) "context" $) | nindent 2 }}
spec:
  targetRef:
    group: {{ $item.targetRef.group | default "gateway.networking.k8s.io" }}
    kind: {{ $item.targetRef.kind | default "Gateway" }}
    name: {{ $item.targetRef.name }}
    {{- if $item.targetRef.namespace }}
    namespace: {{ $item.targetRef.namespace }}
    {{- end }}
    {{- if $item.targetRef.sectionNames }}
    sectionNames:
      {{- toYaml $item.targetRef.sectionNames | nindent 6 }}
    {{- end }}
  {{- if $item.webApplicationFirewall }}
  webApplicationFirewall:
    id: {{ $item.webApplicationFirewall.id }}
  {{- end }}
{{- end }}
{{- end }}
