{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "generic.fullname" . }}
  namespace: {{ default (include "generic.namespace" .) .Values.podMonitor.namespace }}
  labels:
    {{- include "generic.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    {{- with .Values.podMonitor.labels }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.podMonitor.annotations .Values.commonAnnotations) "context" $) | fromYaml }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "generic.labels.matchLabels" (dict "customLabels" .Values.podLabels "context" $) | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "generic.namespace" . | quote }}
  podMetricsEndpoints:
    {{- range .Values.podMonitor.podMetricsEndpoints }}
    - {{- if .port }}
      port: {{ .port }}
      {{- end }}
      {{- if .path }}
      path: {{ .path }}
      {{- end }}
      {{- if $.Values.podMonitor.interval }}
      interval: {{ $.Values.podMonitor.interval }}
      {{- end }}
      {{- if $.Values.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ $.Values.podMonitor.scrapeTimeout }}
      {{- end }}
      {{- if $.Values.podMonitor.honorLabels }}
      honorLabels: true
      {{- end }}
      {{- with $.Values.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.podMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
