{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  namespace: {{ include "redis.namespace" . }}
  labels:
    {{- include "redis.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $password := include "common.secrets.manage" (dict "secret" (include "redis.fullname" .) "key" "redis-password" "providedValues" (list "auth.password") "length" 16 "strong" true "context" $) }}
  redis-password: {{ $password }}
  redis-host: {{ printf "%s.%s.svc.%s" (include "redis.fullname" .) (include "redis.namespace" .) .Values.clusterDomain | b64enc | quote }}
  redis-port: {{ (include "redis.port" .) | b64enc | quote }}
  redis-uri: {{ printf "redis://default:%s@%s.%s.svc.%s:%s" ($password | b64dec) (include "redis.fullname" .) (include "redis.namespace" .) .Values.clusterDomain (include "redis.port" .) | b64enc | quote }}
{{- end }}
